[package]
name = "kubeconf"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
base64 = "0.22"
log = "0.4.27"
colored = "3.0.0"
tabled = "0.20.0"
